#!/bin/bash

unset CPATH
unset C_INCLUDE_PATH
unset CPLUS_INCLUDE_PATH
unset OBJC_INCLUDE_PATH
unset LIBS
unset DYLD_FALLBACK_LIBRARY_PATH
unset DYLD_FALLBACK_FRAMEWORK_PATH
unset CPP
unset CXXCPP

if [ -z $ARCH ]; then
    export ARCH=armv7
fi

if [ -z $SDKVER ]; then
    export SDKVER="6.1"
fi

if [ -z $DEVROOT ]; then
    export DEVROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer"
fi

if [ -z $SDKROOT ]; then
    export SDKROOT="$DEVROOT/SDKs/iPhoneOS$SDKVER.sdk"
fi

#export BUILD_DARWIN_VER=10
export BUILD_DARWIN_VER=`uname -r`
#export PKG_CONFIG_PATH=$SDKROOT/usr/lib/pkgconfig:$DEVROOT/usr/lib/pkgconfig
export PKG_CONFIG_PATH=$SDKROOT/usr/lib/pkgconfig:$DEVROOT/usr/lib/pkgconfig:$PFX/lib/pkgconfig
export AS="$DEVROOT/usr/bin/as"
export ASCPP="$DEVROOT/usr/bin/as"
export AR="$DEVROOT/usr/bin/ar"
export RANLIB="$DEVROOT/usr/bin/ranlib"
export CFLAGS="-arch $ARCH -pipe -no-cpp-precomp -isysroot $SDKROOT --sysroot $SDKROOT -I$SDKROOT/usr/include -I$PFX/include"
#export CFLAGS="-arch $ARCH -pipe -no-cpp-precomp -isysroot $SDKROOT --sysroot $SDKROOT -I$SDKROOT/usr/include -I$PFX/include -I$PFX/include/speex -I$PFX/include/FLAC -I$PFX/include/FLAC++ -I$PFX/include/lame -I$PFX/include/libmms -I$PFX/include/ogg -I$PFX/include/oggz -I$PFX/include/theora -I$PFX/include/vorbis"
#export CFLAGS="$CFLAGS"

#export CPP="$DEVROOT/usr/llvm-gcc-4.2/bin/llvm-cpp-4.2"
export CXX="$DEVROOT/usr/llvm-gcc-4.2/bin/llvm-g++-4.2"
#export CXXCPP="$DEVROOT/usr/llvm-gcc-4.2/bin/llvm-cpp-4.2"
export CC="$DEVROOT/usr/llvm-gcc-4.2/bin/llvm-gcc-4.2"

export LD=$DEVROOT/usr/bin/ld
export AR=$DEVROOT/usr/bin/ar
export AS=$DEVROOT/usr/bin/as
export NM=$DEVROOT/usr/bin/nm
export RANLIB=$DEVROOT/usr/bin/ranlib
export LDFLAGS="-L$SDKROOT/usr/lib/ -L$PFX/lib/"

export CPPFLAGS=$CFLAGS
export CXXFLAGS=$CFLAGS
export CCFLAGS=$CFLAGS

if [ ! \( -d "$DEVROOT" \) ] ; then
   echo "The iPhone SDK could not be found. Folder \"$DEVROOT\" does not exist."
   exit 1
fi

if [ ! \( -d "$SDKROOT" \) ] ; then
   echo "The iPhone SDK could not be found. Folder \"$SDKROOT\" does not exist."
   exit 1
fi

echo "Configuring for architecture: $ARCH..."
echo "SDK Version: $SDKVER"
echo "DevRoot: $DEVROOT"

./configure --build="$ARCH-apple-darwin$BUILD_DARWIN_VER" --host="arm-apple-darwin10" --enable-static --disable-shared ac_cv_file__dev_zero=no ac_cv_func_setpgrp_void=yes $@
